services:
  - type: web
    name: careway-backend
    plan: free
    runtime: docker
    region: frankfurt
    healthCheckPath: /patients
    
    envVars:
      - key: GMAIL_PASSWORD
        scope: secret
      - key: SPRING_PROFILES_ACTIVE
        value: render
