spring.application.name=backend
server.port=${PORT:8081}
spring.sql.init.encoding=UTF-8
# DEV: S'exécute toujours pour charger les données de test
spring.sql.init.mode=ALWAYS
spring.datasource.url=jdbc:h2:file:C:/Users/user/Downloads/BackendCareWay/data/testdb
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.defer-datasource-initialization=true
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Configuration Gmail pour l'envoi d'emails
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=askrichayma7@gmail.com
spring.mail.password=wsqbnpyvgefdlpyx
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000
