spring.application.name=backend
# Le port sur lequel est lancee l'application web (8081 pour correspondre au frontend)
server.port=${PORT:8081}
# Encodage des scripts sql d'initialisation de la BD : data.sql, schema.sql
spring.sql.init.encoding=UTF-8
# NEVER = data.sql s'exécute seulement à la première création (persistence des modifications)
spring.sql.init.mode=NEVER
# Configuration de la source de données H2 - MODE FICHIER PERSISTANT (chemin absolu)
spring.datasource.url=jdbc:h2:file:C:/Users/user/Downloads/BackendCareWay/data/testdb
# On crée d'abord le schema relationnel à partir des annotations JPA
# Utiliser "update" pour conserver les données entre les redémarrages
spring.jpa.hibernate.ddl-auto=update
# Desactiver les logs Hibernate
spring.jpa.show-sql=false
logging.level.org.hibernate=WARN
# On initialise ensuite la BD (data.sql)
spring.jpa.defer-datasource-initialization=true
# Pour voir les requêtes SQL dans la console
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Configuration Gmail pour l'envoi d'emails
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=askrichayma7@gmail.com
spring.mail.password=wsqbnpyvgefdlpyx
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000
